using Riok.Mapperly.Abstractions;
using BookingService.Data.Features.Auth.RefreshTokens;

namespace BookingService.Web.Features.Auth.Dtos.RefreshTokens;

[Mapper]
public static partial class RefreshTokenEntityDtoMapper
{
    [MapperIgnoreSource(nameof(RefreshTokenEntity.Id))]
    [MapperIgnoreSource(nameof(RefreshTokenEntity.User))]
    [MapperIgnoreSource(nameof(RefreshTokenEntity.UserId))]
    public static partial RefreshTokenDto ToDto(this RefreshTokenEntity entity); //Source-generated by Mapperly
    public static partial IEnumerable<RefreshTokenDto> ToDtos(this IEnumerable<RefreshTokenEntity> entities); //Source-generated by Mapperly

    [MapperIgnoreSource(nameof(RefreshTokenEntity.Id))]
    [MapperIgnoreSource(nameof(RefreshTokenEntity.User))]
    [MapperIgnoreSource(nameof(RefreshTokenEntity.UserId))]
    public static partial void MapToDto(this RefreshTokenEntity source, RefreshTokenDto destination); //Source-generated by Mapperly
    public static partial void MapToDto(this RefreshTokenDto source, RefreshTokenDto destination); //Source-generated by Mapperly
    public static partial IQueryable<RefreshTokenDto> ProjectToDto(this IQueryable<RefreshTokenEntity> query); //Source-generated by Mapperly
}