<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Respawn" Version="7.0.0" />
    <PackageReference Include="TUnit" Version="1.6*" />
    <PackageReference Include="TUnit.Aspire" Version="1.66.27" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BookingService.AppHost\BookingService.AppHost.csproj" />
    <ProjectReference Include="..\BookingService.Web\BookingService.Web.csproj" />
  </ItemGroup>

</Project>
