using Riok.Mapperly.Abstractions;
using BookingService.Data.Features.Bookings;

namespace BookingService.Web.Features.Bookings.Dtos;

[Mapper]
public static partial class BookingEntityDtoMapper
{
    [UserMapping]
    private static TimeSpan GetBookingDuration(BookingEntity entity)
    {
        return entity.BookingEnd - entity.BookingStart;
    }

    [UserMapping]
    private static DateTimeOffset GetBookingEnd(BookingDto dto)
    {
        return dto.BookingStart + dto.BookingDuration;
    }

    [MapperIgnoreSource(nameof(BookingEntity.User))]
    [MapperIgnoreSource(nameof(BookingEntity.Room))]
    [MapPropertyFromSource(nameof(BookingDto.BookingDuration))]
    public static partial BookingDto ToDto(this BookingEntity source); //Source-generated by Mapperly
    public static partial IEnumerable<BookingDto> ToDtos(this IEnumerable<BookingEntity> sources); //Source-generated by Mapperly

    [MapperIgnoreSource(nameof(BookingEntity.User))]
    [MapperIgnoreSource(nameof(BookingEntity.Room))]
    [MapPropertyFromSource(nameof(BookingDto.BookingDuration))]
    public static partial void MapToDto(this BookingEntity source, BookingDto destination); //Source-generated by Mapperly
    public static partial void MapToDto(this BookingDto source, BookingDto destination); //Source-generated by Mapperly
    public static partial IQueryable<BookingDto> ProjectToDto(this IQueryable<BookingEntity> query); //Source-generated by Mapperly

    [MapperIgnoreSource(nameof(BookingDto.UserId))]
    [MapperIgnoreTarget(nameof(BookingEntity.User))]
    [MapperIgnoreTarget(nameof(BookingEntity.Room))]
    [MapperIgnoreTarget(nameof(BookingEntity.UserId))]
    [MapPropertyFromSource(nameof(BookingEntity.BookingEnd))]
    public static partial BookingEntity ToEntity(this BookingDto source); //Source-generated by Mapperly
    public static partial IEnumerable<BookingEntity> ToEntities(this IEnumerable<BookingDto> sources); //Source-generated by Mapperly

    [MapperIgnoreSource(nameof(BookingDto.UserId))]
    [MapperIgnoreTarget(nameof(BookingEntity.User))]
    [MapperIgnoreTarget(nameof(BookingEntity.Room))]
    [MapperIgnoreTarget(nameof(BookingEntity.UserId))]
    [MapPropertyFromSource(nameof(BookingEntity.BookingEnd))]
    public static partial void MapToEntity(this BookingDto source, BookingEntity destination); //Source-generated by Mapperly
    public static partial void MapToEntity(this BookingEntity source, BookingEntity destination); //Source-generated by Mapperly
}