using Riok.Mapperly.Abstractions;
using BookingService.Data.Features.Auth.Users;

namespace BookingService.Web.Features.Auth.Dtos.Users;

[Mapper]
public static partial class UserEntityDtoMapper
{
    public static UserDto ToDto(this UserEntity source)
    {
        return new UserDto()
        {
            Id = source.Id,
            Email = source.Email!
        };
    }
    public static partial IEnumerable<UserDto> ToDtos(this IEnumerable<UserEntity> sources); //Source-generated by Mapperly
    public static void MapToDto(this UserEntity source, UserDto destination)
    {
        destination.Id = source.Id;
        destination.Email = source.Email!;
    }
    public static partial void MapToDto(this UserDto source, UserDto destination); //Source-generated by Mapperly
    public static partial IQueryable<UserDto> ProjectToDto(this IQueryable<UserEntity> query); //Source-generated by Mapperly
}