using Riok.Mapperly.Abstractions;
using BookingService.Data.Features.Rooms;
using BookingService.Data.Features.Bookings;

namespace BookingService.Web.Features.Rooms.Dtos;

[Mapper]
public static partial class RoomEntityDtoMapper
{
    [UserMapping]
    private static List<Guid> MapBookings(List<BookingEntity> entities)
    {
        return entities.Select(e => e.Id).ToList();
    }

    public static partial RoomDto ToDto(this RoomEntity source); //Source-generated by Mapperly
    public static partial IEnumerable<RoomDto> ToDtos(this IEnumerable<RoomEntity> sources); //Source-generated by Mapperly
    public static partial void MapToDto(this RoomEntity source, RoomDto destination); //Source-generated by Mapperly
    public static partial void MapToDto(this RoomDto source, RoomDto destination); //Source-generated by Mapperly
    public static partial IQueryable<RoomDto> ProjectToDto(this IQueryable<RoomEntity> query); //Source-generated by Mapperly

    [MapperIgnoreSource(nameof(RoomDto.Bookings))]
    [MapperIgnoreTarget(nameof(RoomEntity.Bookings))]
    public static partial RoomEntity ToEntity(this RoomDto source); //Source-generated by Mapperly
    public static partial IEnumerable<RoomEntity> ToEntities(this IEnumerable<RoomDto> sources); //Source-generated by Mapperly

    [MapperIgnoreSource(nameof(RoomDto.Bookings))]
    [MapperIgnoreTarget(nameof(RoomEntity.Bookings))]
    public static partial void MapToEntity(this RoomDto source, RoomEntity destination); //Source-generated by Mapperly
    public static partial void MapToEntity(this RoomEntity source, RoomEntity destination); //Source-generated by Mapperly
}